services:
  lutetium-db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: 'lutetium'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - lutetium-db-volume:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  lutetium-db-volume:
